export const UPDATE_MODEL_EVENT = "update:modelValue"
export const CHANGE_EVENT = "change"
export const INPUT_EVENT = "input"
export const BLUR_EVENT = "blur"
export const FOCUS_EVENT = "focus"
export const CLEAR_EVENT = "clear"
